# Generated by Django 4.2 on 2023-06-17 05:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('f7ecab62-a40a-4082-8e3f-f7bfe8ede5f0'), unique=True),
        ),
    ]
