# Generated by Django 4.2 on 2023-06-17 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('im', '0002_good_public_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_place_point', models.DateTimeField(auto_created=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.UUID('09ab013b-9e34-4f8d-ae45-013eb7ce8df0'), unique=True)),
                ('order_number', models.CharField(blank=True, max_length=15)),
                ('discount', models.DecimalField(decimal_places=3, max_digits=4)),
                ('additional_information', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_change_point', models.DateTimeField(auto_created=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_change_orders', to='crm.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_change_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.CharField(max_length=10)),
                ('locality_type', models.CharField(blank=True, max_length=15)),
                ('locality', models.CharField(blank=True, max_length=35)),
                ('max_weight', models.DecimalField(blank=True, decimal_places=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.post')),
            ],
            options={
                'unique_together': {('zip', 'locality')},
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.UUID('1aa2a60c-2409-40b4-b705-4f824d70cd83'), unique=True)),
                ('status_name', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_line_good', to='im.good')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_line_order', to='crm.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=15)),
                ('district', models.CharField(blank=True, max_length=25)),
                ('street_type', models.CharField(blank=True, max_length=35)),
                ('street', models.CharField(blank=True, max_length=35)),
                ('building', models.CharField(blank=True, max_length=7)),
                ('apartment', models.CharField(blank=True, max_length=7)),
                ('post_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.postoffice')),
            ],
        ),
    ]
