# Generated by Django 4.2 on 2023-06-15 03:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=1234567890, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('ea3b2efe-8bc5-4e4b-9ffa-972a81686882'), unique=True),
        ),
    ]
