# Generated by Django 4.2 on 2023-06-15 03:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_phone_alter_user_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('b7d8fe52-89ef-4b97-90a3-cde2c65907d1'), unique=True),
        ),
    ]
