# Generated by Django 4.2 on 2023-06-15 05:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_phone_alter_user_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('0ea300f5-17e8-40b7-bcd7-b942d2d985ea'), unique=True),
        ),
    ]
